trigger:
- master
- azure-devops

phases:
#################################################
- phase: windows
#################################################
  condition: succeeded()
  queue: Hosted VS2017

  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_9_x:
        node_version: 9.x
################################################################################
  steps:
  # set Node.JS version
  - task: NodeTool@0
    inputs:
      version: $(node_version)
  # install
  - script: npm config set package-lock false
  - task: Npm@1
    displayName: npm install
    inputs:
      command: install

  # lint
  - script: npm run ci-lint
    displayName: npm lint
#    workingDirectory: powershell

  # test
  - script: npm run ci-test
    displayName: npm test
#    workingDirectory: powershell


#################################################
- phase: linux
#################################################
  condition: succeeded()
  queue: Hosted Linux Preview

  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_9_x:
        node_version: 9.x
################################################################################
  steps:
  # set Node.JS version
  - task: NodeTool@0
    inputs:
      version: $(node_version)
  # install
  - script: npm config set package-lock false
  - task: Npm@1
    displayName: npm install
    inputs:
      command: install
#      workingDir: node

  # lint
  - script: npm run ci-lint
#    workingDirectory: node
    displayName: npm lint

  # test
  - script: npm run ci-test
    displayName: npm test
#    workingDirectory: node

#################################################
- phase: macOS
#################################################
  condition: succeeded()
  queue: Hosted macOS Preview

  steps:
  ################################################################################

  # install
  - script: npm config set package-lock false
  - task: Npm@1
    displayName: npm install
    inputs:
      command: install
#      workingDir: node

  # lint
  - script: npm run ci-lint
    displayName: npm lint
#    workingDirectory: node

  # test
  - script: npm run ci-test
    displayName: npm test
#    workingDirectory: node
