queue:
  name: Hosted Ubuntu 1604
  demands: npm

steps:
- script: |
    npm config set package-lock false
    npm install
    npm run ci-lint
    npm run ci-test
  workingDirectory: ~/workspace
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false