trigger:
- master

#strategy:
#  matrix:
#    node_8_x:
#      node_version: 8.x
#    node_9_x:
#      node_version: 9.x
#    node_10_x:
#      node_version: 10.x



phases:
#################################################
- phase: windows
#################################################
  condition: and(succeeded(), ne(variables.skip_windows, true))
  queue: Hosted VS2017
################################################################################
  variables:
    node_version: {variables.node_version}
  steps:
  # set Node.JS version
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
#      versionSpec: 10.x
  # install
  - script: npm config set package-lock false
  - task: Npm@1
    displayName: npm install
    inputs:
      command: install

  # lint
  - script: npm run ci-lint
    displayName: npm lint
#    workingDirectory: powershell

  # test
  - script: npm run ci-test
    displayName: npm test
#    workingDirectory: powershell


#################################################
- phase: linux
#################################################
  condition: and(succeeded(), ne(variables.skip_linux, true))
  queue: Hosted Linux Preview
################################################################################
  variables:
    node_version: {variables.node_version}
  steps:
  # set Node.JS version
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
  # install
  - script: npm config set package-lock false
  - task: Npm@1
    displayName: npm install
    inputs:
      command: install
#      workingDir: node

  # lint
  - script: npm run ci-lint
#    workingDirectory: node
    displayName: npm lint

  # test
  - script: npm run ci-test
    displayName: npm test
#    workingDirectory: node

#################################################
- phase: macOS
#################################################
  condition: and(succeeded(), ne(variables.skip_darwin, true))
  queue: Hosted macOS Preview

  steps:
  ################################################################################

  # install
  - script: npm config set package-lock false
  - task: Npm@1
    displayName: npm install
    inputs:
      command: install
#      workingDir: node

  # lint
  - script: npm run ci-lint
    displayName: npm lint
#    workingDirectory: node

  # test
  - script: npm run ci-test
    displayName: npm test
#    workingDirectory: node
